### ISSUE TITLE
Confirmation link expired? Blank links on notifications

### ISSUE THREAD

**Issue by Reedyseth** [stcr/subscribe-to-comments-reloaded#250]
Issue reported here:

https://wordpress.org/support/topic/confirmation-link-expired?replies=4#post-8824111

Original message:

> Hi there!
> 
> Thanks for the helpful plugin. I'm running into an issue in testing this afternoon where when I click on the subscription confirmation link, even seconds after it hitting my inbox, it says it's expired.
> 
> When I click it, it sends me to a page that says:
> 
> "Woohaa the link to manage your subscriptions has expired, don’t worry, just enter your email below and a new link will be send."
> 
> When I enter my email into the form provided, the system sends me a completely blank email with the subject line "Manage your subscriptions on [site name]".
> 
> I can't find where to edit the expired link page (to fix the typos) or why it would be "expired" in the first place less than 30 seconds after being generated.
> 
> Thanks for your help!

**Comment by Reedyseth** [comment]
After checking your your plugins settings I found two issues, the links are broken and the management messages are a little bit wrong, so to fix them please do the following.

Update any tag that refers to a link like this image:

![image](https://cloud.githubusercontent.com/assets/1228711/18150190/30bc4dc6-6fa2-11e6-8024-5c8018eb7477.png)

or you can click the gear icon and setting up there:

![image](https://cloud.githubusercontent.com/assets/1228711/18150212/62c56794-6fa2-11e6-931c-669ca0c4ef35.png)

You have to repeat this steps for every link that you have in your comments and notifications, everywhere that you have a StCR link tag.

---

As for the message

do this this tab:

![image](https://cloud.githubusercontent.com/assets/1228711/18150279/df7acd92-6fa2-11e6-9b7e-66e9cd0d9857.png)


Go to the field **Management Page message**, this Field is to display the notification request to a user and it only parse the `[blog_name]` tag.

![image](https://cloud.githubusercontent.com/assets/1228711/18028344/79aebeae-6c39-11e6-8e48-3a4cea1ae026.png)

The field Management **Email message** is use for the email notification, in that field you can use the `[blog_name]` and `[manager_link]`. This where the link will be render.

![image](https://cloud.githubusercontent.com/assets/1228711/18028347/91e800d4-6c39-11e6-9260-a15d9623a586.png)

After setting you site with those settings everything should work.

**Comment by nickloper** [comment]
Thanks. I've updated those links, but the confirmation link is still giving me that expired message when I click on it, and no way to subscribe to the desired comment thread after inputting my email to request the manage subscriptions page. 

![image](https://cloud.githubusercontent.com/assets/21373843/18150704/da286a34-6f9d-11e6-9023-52956c47b3d9.png)

Here's what I see after I click the confirmation link:

![image](https://cloud.githubusercontent.com/assets/21373843/18150789/621c7476-6f9e-11e6-8dc5-7e6140764181.png)

**Comment by Reedyseth** [comment]
I see, in the mean time please deactivate and activate the plug in.

**Comment by nickloper** [comment]
Thanks Israel, deactivated and activated again, but I'm still getting the
same "expired" link error message when I click on the confirm subscription
link.

**Comment by Reedyseth** [comment]
@nickloper ,

I see that the subscribers email key is not being generated, do you have access to you database to make a change?

**Comment by nickloper** [comment]
I'm not sure ... which probably means no. If you have specific instructions
I'll see what I can do.
ᐧ

**Comment by Reedyseth** [comment]
@nickloper Thank you, I found the problem and I am working on it :+1:

**Comment by Reedyseth** [comment]
@nickloper I have added the fixe,

Would you like to download the code and test it ?

https://github.com/stcr/subscribe-to-comments-reloaded/archive/development.zip

**Comment by Reedyseth** [comment]
@nickloper I released the new update so please update.!!

**Comment by nickloper** [comment]
When I try to upload the zip file to my dashboard I get this error:

Installing Plugin from uploaded file:
subscribe-to-comments-reloaded-development.zip

Unpacking the package…

Installing the plugin…

The package could not be installed. No valid plugins were found.

Plugin install failed.
ᐧ

On Fri, Sep 2, 2016 at 7:01 PM, Israel Barragan C. <notifications@github.com

**Comment by Reedyseth** [comment]
Hi Nick, that happened because you tried to upload the GitHub zip file,
within that file there is another folder name
`Subscribe-to-comments-reloaded`, you have to make that folder a zip file
or you can download the correct file from the WordPress plugin site, just
click the orange button where the 160902 version is labeled.

**Comment by nickloper** [comment]
OK, installed version 160902 now.

Now when I click the confirmation link, I don't get the confirmation link
expired error, but I get this page that still doesn't give me confirmation
I'm subscribed to the comment thread. Here's what it says:

Manage subscriptions

In order to cancel or suspend one or more notifications, select the
corresponding checkbox(es) and click on the button at the end of the list.

No subscriptions match your search criteria.
ᐧ

On Mon, Sep 5, 2016 at 9:05 PM, Israel Barragan C. <notifications@github.com
> wrote:

> Hi Nick, that happened because you tried to upload the GitHub zip file,
> within that file there is another folder name
> `Subscribe-to-comments-reloaded`, you have to make that folder a zip file
> or you can download the correct file from the WordPress plugin site, just
> click the orange button where the 160902 version is labeled.

**Comment by Reedyseth** [comment]
OK, can you send me that link to my email and also the settings that you have in the menu option, under the **StCR System** menu. I will check how things are, use:

reedyseth {at) gmail }dot[ com

**Comment by Merllin** [comment]
Hello,

I had a similar problem using version 160915: the email confirmation link doesn't display the confirmation page for subscription.

I made a change in **stcr_manage.php**, on line 124 **srek** instead of **sre**:
`$manager_link .= ( ( strpos( $manager_link, '?' ) !== false ) ? '&' : '?' ) . "srek=" . $this->utils->get_subscriber_key( $clean_email ) . "&srk=$subscriber_salt";`
and now is working fine, I get the confirmation page.

@nickloper, you could give it a try

Regards

**Comment by nickloper** [comment]
When I make that change and re-enable the plugin, I get the confirmation
email and click on the link, it takes me to this page:

Manage subscriptions

In order to cancel or suspend one or more notifications, select the
corresponding checkbox(es) and click on the button at the end of the list.
You are currently subscribed to:

No subscriptions match your search criteria.


Disabling again.
ᐧ

**Comment by Merllin** [comment]
It seems you are receiving the [manager_link], not the [confirm_link]

Your confirmation link look like this?
domain.com/comment-subscriptions/**?srek=**a9...a032e**&srk=**59...257**&srp=**49906**&sra=c**

**Comment by Merllin** [comment]
If you disable the double check are you subscribed to comments?
If not, it's possible to have a conflict between plugin and database. You should check your error_log and post the error here.

Regards
