### ISSUE TITLE
Bug Report: No check box after update

### ISSUE THREAD

**Issue by scarbit** [stcr/subscribe-to-comments-reloaded#256]
Hi,

With this last version the check-box for subscribing is not appearing anymore.
Everything worked  just fine with previous version(s).
Please see options below (this is a fresh new installation of the plug in)

By manually adding the code in the comments template I end up with a check-box and a link to subscribe without commenting but:
1: notification e-mails are not sent.
2: it fails to identify the user session (or something like this) because it is asking the users to enter theirs email address. 

Any ideas?

Thanks,
Alex

![image](https://cloud.githubusercontent.com/assets/20117227/18203297/d3d8b274-711e-11e6-8d1d-864dac4d3a97.png)

![image](https://cloud.githubusercontent.com/assets/20117227/18203304/ddf10e46-711e-11e6-82fb-df6afa2a48f4.png)

**Comment by Reedyseth** [comment]
hI @scarbit ,

Thank you for reporting the issue, on this new Update StCR rely in your WordPress setup standarization, if the theme that you are using does not fit the WordPress standar then it will break, you can test this by activating any of the WordPress built-in themes.

As for the other issues I have fixed them and releasing the update during the day.

**Comment by scarbit** [comment]
Hi Reedyseth,

Thanks for the reply and for the update.

Unfortunately I am still experiencing the No.1 and No.2 issues.
![image](https://cloud.githubusercontent.com/assets/20117227/18222799/1d41b3fc-71ab-11e6-81fb-0d0df7c3fa58.png)

Please advise!

Br,
Alex

**Comment by Reedyseth** [comment]
Hi Alex, two questions. What is your site URL? And what version are you running right now?. Please deactivate and activate the plugin.

**Comment by scarbit** [comment]
Hi Reedyseth,

The site url is http://www.trafictube.ro
Second one:
![image](https://cloud.githubusercontent.com/assets/20117227/18224791/e88d6798-71e9-11e6-8693-cc068bb9b536.png)

WordPress 4.6
STCRT management URL is the default one: /comment-subscriptions

On a second note, the authors are automatically subscribed to comments.
Br,
Alex

**Comment by manu-p** [comment]
I'm facing the same issue on a wp site and not ready to change theme...

@scarbit "_By manually adding the code in the comments template I end up with a check-box and a link to subscribe without commenting_".

Do you mind explaining what code you added in comments.php (I guess) and at what line ?

**Comment by Reedyseth** [comment]
@manu-p ,

You can add manually the checkbox with:

`<?php global $wp_subscribe_reloaded; if (isset($wp_subscribe_reloaded)){ $wp_subscribe_reloaded->stcr->subscribe_reloaded_show(); } ?>`

**Comment by manu-p** [comment]
@Reedyseth : thank you ! Works better. :-)

Now I get trouble with the [subscribe_link]. I'm using it to allow people to subscribe to comments without commenting themselves, and from what I understood it is used to manage subscriptions too.

I followed the explanation found [here](http://behstant.com/subscribe-reloaded/realMgnPage.php) but so far I just get the following when I click in the link : 
Fatal error: Call to undefined method stcr\stcr_subscribe_reloaded::subscribe_reloaded_manage() in /_blabla_/htdocs/wp-content/themes/surreal/subscribe.php on line 3

Here's what I get in subscribe.php:
`<?php
/* Template Name: Subscribe To Comments */
if (isset($wp_subscribe_reloaded)){ global $posts; $posts = $wp_subscribe_reloaded->subscribe_reloaded_manage(); }
?> 
`
Line 3 is the one beginning with if (isset...

**Comment by manu-p** [comment]
OK, I just edited subscribe.php to: 
`<?php global $wp_subscribe_reloaded; if (isset($wp_subscribe_reloaded)){ global $posts; $posts = $wp_subscribe_reloaded->stcr->subscribe_reloaded_manage(); } ?> `

Now I get an empty page when I click in the [subscribe_link] (and [manager_link] too).

The corresponding URL is http://mysite/abonnements?srp=2230&srk=1b7633a75f52a8dde61895d3f2ea5d8b

The 'abonnements' page exists in mysite, with 'Subscribe to Comments' template.

**Comment by Reedyseth** [comment]
Hi @manu-p to make those links works follow this tutorial:

https://www.youtube.com/watch?v=eFW-2NIRzBA

Also don't miss this other tutorial:

https://www.youtube.com/watch?v=yRxOY8yq_cc

**Comment by Reedyseth** [comment]
> I followed the explanation found here but so far I just get the following when I click in the link : 
> Fatal error: Call to undefined method stcr\stcr_subscribe_reloaded::subscribe_reloaded_manage() in /blabla/htdocs/wp-content/themes/surreal/subscribe.php on line 3

As for that link, it is outdated, you can use this one instead: 

https://github.com/stcr/subscribe-to-comments-reloaded/wiki/KB#Real-Page
