### ISSUE TITLE
Couldn\’t find an email with the SRE key

### ISSUE THREAD

**Issue by JRabDawg** [stcr/subscribe-to-comments-reloaded#278]
This error has been cascading multiple times a day for about a week now in this log:

/wp-content/plugins/subscribe-to-comments-reloaded/utils/log.txt

[ERROR][2016-09-21 13:14:43] – Couldn\’t find an email with the SRE key: ( )

[ERROR][2016-09-29 13:32:33] – Couldn\’t find an email with the SRE key: ( )

[ERROR][2016-09-29 13:33:47] – Couldn\’t find an email with the SRE key: ( )

[ERROR][2016-09-29 13:34:11] – Couldn\’t find an email with the SRE key: ( )

[ERROR][2016-09-29 13:34:40] – Couldn\’t find an email with the SRE key: ( )

[ERROR][2016-09-29 13:35:43] – Couldn\’t find an email with the SRE key: ( )

And when someone goes to subscribe to a post, they don’t get any email confirmation, etc.

On WordPress v4.6 and StCR v160915

All settings are default on the pluggin.

---------------------------------------------
I can see in the log when this error also prints when it attempts to send emails. It appears something is broken with it in regards to doing email. Any ideas?
----------------------------------------------
It appears that when it’s doing the lookup for any email addresses with an associated email_key, it for some reason is looking for an empty key string versus an actual key. Not sure if this is what’s happening or not, but would appreciate any suggestions if this isn’t a bug in the plugin. thanks!
------------------------------------------------
The error prints when clicking on “subscribe”:

Notify me of followup comments via e-mail. You can also subscribe without commenting.

---------------------------------------------------

Thanks

**Comment by Reedyseth** [comment]
@JRabDawg 

> And when someone goes to subscribe to a post, they don’t get any email confirmation, etc

In order to get a confirmation link you have to enable the **double check** options:

![image](https://cloud.githubusercontent.com/assets/1228711/18968407/15cef8be-8646-11e6-9193-0ff32e4d5e0e.png)

> It appears that when it’s doing the lookup for any email addresses with an associated email_key, it for some reason is looking for an empty key string versus an actual key. Not sure if this is what’s happening or not, but would appreciate any suggestions if this isn’t a bug in the plugin.
> 
> The error prints when clicking on “subscribe”:
> Notify me of followup comments via e-mail. You can also subscribe without commenting.

This happend when for some reason the SRE key is not send in the query string, you don't have to worry about, unless you are having issues with the plugin like problems whille manageging the comments or subscribing.

**Comment by JRabDawg** [comment]
I just tried that, but it still isn't fixed. Error in log and no email received.

**Comment by Reedyseth** [comment]
I see, there is an error on the latest version, I have fixed that already on the development code. If you could test the development version that would be awesome.

Please download it from here:

https://github.com/stcr/subscribe-to-comments-reloaded/archive/development.zip

**Comment by JRabDawg** [comment]
Just clicking on the subscribe link on a post page before even entering an email address on the manage page causes the error:

![image](https://cloud.githubusercontent.com/assets/22529222/18968979/36a3b0da-8659-11e6-8226-2cf82dfa7002.png)

**Comment by JRabDawg** [comment]
Copied up the files in the zip and overwrote what was there. Same error during execution shown above.

**Comment by JRabDawg** [comment]
I am getting emails once entered now, so that's good, but the error still is in the logs from the above screenshot execution.

**Comment by Reedyseth** [comment]
> but the error still is in the logs from the above screenshot execution.

Yes, I will work on those messages, for now you can ignore them.
